server:
  port: 8087

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/streamingdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password123}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

http:
  logging:
    enabled: true
    level: DEBUG 